### ISSUE TITLE
Library import fails throwing ambiguous errors

### ISSUE THREAD

**Issue by rishighan** [rishighan/threetwo#11]
Courtesy of @btxgit:

The current issues I see:

1. When I move new dirs into the comic directory, it appears to be queueing cover generation, but it tries to make the covers dir undefined.

```console

Example log output:

Error: Command failed: /opt/calibre/ebook-meta "undefined/undefinedundefined" --get-cover "/threetwo-import-service/userdata/covers/undefined/undefined_cover.jpg"
import                 | Traceback (most recent call last):
import                 |   File "runpy.py", line 194, in _run_module_as_main
import                 |   File "runpy.py", line 87, in _run_code
import                 |   File "site.py", line 45, in <module>
import                 |   File "site.py", line 41, in main
import                 |   File "calibre/ebooks/metadata/cli.py", line 180, in main
import                 | FileNotFoundError: [Errno 2] No such file or directory: 'undefined/undefinedundefined'
import                 |
import                 |     at ChildProcess.exithandler (child_process.js:383:12)
import                 |     at ChildProcess.emit (events.js:400:28)
import                 |     at maybeClose (internal/child_process.js:1058:16)
import                 |     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5) {
import                 |   killed: false,
import                 |   code: 1,
import                 |   signal: null,
import                 |   cmd: '/opt/calibre/ebook-meta "undefined/undefinedundefined" --get-cover "/threetwo-import-service/userdata/covers/undefined/undefined_cover.jpg"'
```

Resolves after reducing the set of books to approx 3k

2. At least on the mac platform, the dir walker process appears to attempt to pass along too many file / paths and NATS fails. Resolves after restarting import

3. (maybe) I thought you were saving/loading settings, but the only settings I see are for AirDC++ (just teh first airdc++ item)

**Comment by rishighan** [comment]
@btxgit can add more details, but replacing `NATS` with `Redis` as the transporter in `threetwo-import-service` seems to help the import process get past the `Maximum payload violation` error.

**Comment by rishighan** [comment]
Going to close this issue now. @kingfenix's issue with the import was mostly related to network shares, and completely orthogonal to this particular issue. I think for you, @btxgit, the issue was solved. Please re-open if that's not the case.
