### ISSUE TITLE
Moving comic-filled dirs into the comics dir seems to extract the cover but everything is set to undefined

### ISSUE THREAD

**Issue by btxgit** [rishighan/threetwo#12]
When I move new dirs (with comics in them) into the shared comic directory, it appears to be queueing up the cover generation (good), but each of the dirs it tries to make have Undefined values, leading me to believe that it's losing the metadata somehow.

docker restart import 

seems to re-do things which complains about the file being in the db already, but then seems to work...

   Example log output:

```
 Error: Command failed: /opt/calibre/ebook-meta "undefined/undefinedundefined" --get-cover "/threetwo-import-service/userdata/covers/undefined/undefined_cover.jpg"
import                 | Traceback (most recent call last):
import                 |   File "runpy.py", line 194, in _run_module_as_main
import                 |   File "runpy.py", line 87, in _run_code
import                 |   File "site.py", line 45, in <module>
import                 |   File "site.py", line 41, in main
import                 |   File "calibre/ebooks/metadata/cli.py", line 180, in main
import                 | FileNotFoundError: [Errno 2] No such file or directory: 'undefined/undefinedundefined'
import                 |
import                 |     at ChildProcess.exithandler (child_process.js:383:12)
import                 |     at ChildProcess.emit (events.js:400:28)
import                 |     at maybeClose (internal/child_process.js:1058:16)
import                 |     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5) {
import                 |   killed: false,
import                 |   code: 1,
import                 |   signal: null,
import                 |   cmd: '/opt/calibre/ebook-meta "undefined/undefinedundefined" --get-cover "/threetwo-import-service/userdata/covers/undefined/undefined_cover.jpg"'

```

**Comment by rishighan** [comment]
Refactored code now:

1. Pushes a `job` into the queue as part of the loop that walks the `comics` directory. In testing currently

2. Logs aggressively. 

3. Makes `bullMQ` central to the import process, which is backed by `redis`
