### ISSUE TITLE
Import failed on main library 70,000 plus comics

### ISSUE THREAD

**Issue by bigredone10** [rishighan/threetwo#25]
During import, the core-services exited with the following error:

Error: ENOENT: no such file or directory, open '/userdata/covers/100 Bullets #82 1999/100 Bullets 082 G85-Megan pg01.jpg'
Emitted 'error' event on ReadStream instance at:
    at internal/fs/streams.js:126:14
    at FSReqCallback.oncomplete (fs.js:179:23) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/userdata/covers/100 Bullets #82 1999/100 Bullets 082 G85-Megan pg01.jpg'
}

**Comment by rishighan** [comment]
As of today, @bigredone10 reported a successful import of roughly `86k` comics. Keeping this open as a catch-all for all queue-related issues while importing.

**Comment by rishighan** [comment]
Adding @nstephenh to this issue to investigate the reason for import failure.

Some facts:

1. AirDC++ and ThreeTwo are on the same physical box, but one is a linux vm and the other is a freebsd jail.
2. Attempting import of `11.2k folders, 364.8k files` from a `SMB` share
3. Restarted the stack maybe 5 total times over the course of the past few days.
4. Running Truenas
