### ISSUE TITLE
Starting the app with yarn start throws a sass-related error

### ISSUE THREAD

**Issue by rishighan** [rishighan/threetwo#91]
Trying to spin up the app with `yarn start` results in a `sass` dependency error thrown with the following trace:

```
[vite:css] Preprocessor dependency "sass" not found. Did you install it? Try `yarn add -D sass`.
file: /Users/rishi/work/threetwo/src/client/assets/scss/App.scss
error during build:
Error: Preprocessor dependency "sass" not found. Did you install it? Try `yarn add -D sass`.
    at loadPreprocessor (file:///Users/rishi/work/threetwo/node_modules/vite/dist/node/chunks/dep-df561101.js:39269:19)
    at scss (file:///Users/rishi/work/threetwo/node_modules/vite/dist/node/chunks/dep-df561101.js:39310:20)
    at compileCSSPreprocessors (file:///Users/rishi/work/threetwo/node_modules/vite/dist/node/chunks/dep-df561101.js:38735:36)
    at compileCSS (file:///Users/rishi/work/threetwo/node_modules/vite/dist/node/chunks/dep-df561101.js:38785:42)
    at async Object.transform (file:///Users/rishi/work/threetwo/node_modules/vite/dist/node/chunks/dep-df561101.js:38266:56)
    at async transform (file:///Users/rishi/work/threetwo/node_modules/rollup/dist/es/shared/node-entry.js:24367:16)
    at async ModuleLoader.addModuleSource (file:///Users/rishi/work/threetwo/node_modules/rollup/dist/es/shared/node-entry.js:24567:30)
error Command failed with exit code 1.

```

**Comment by rishighan** [comment]
https://github.com/rishighan/threetwo/pull/96/commits/74a9c4bdb0a5aa01353e1060644fbd2a323f1e46 should address this.
